### ISSUE TITLE
Package manager support

### ISSUE THREAD

**Issue by Woomymy** [Woomymy/kelp#15]
I think adding a "package manager integration" sould be nice to install additionnal softwares while setting up the dotfiles

## Example

```yaml
packages:
        arch:
                # with_file: etc/pacman.bak
                install:
                        [
                                "i3-gaps",
                                "polybar" # Maybe add support for AUR helpers?
                        ]
        gentoo:
                # with_file: var/lib/portage/world
                install:
                        [
                                "app-emulation/docker",
                                "x11-wm/i3-gaps"
                        ]
        gems:
                # with_file: home/packages/gems
                install:
                        [
                                "mdl"
                        ]
                # For additionnal package managers like gems
                # we can directly install with distros package manager  

```
Syntax like
Distro / external PM
with_file: file with packages
install: Packages names

## Packages managers to support
- [X] Portage (gentoo's package manager)
- [ ] Pacman
- [ ] APT
- [ ] Dnf
